AenEnterprise/AenEnterprise.FrontEndMvc/Controllers/SalesManagementController.cs
using Microsoft.AspNetCore.Mvc;

namespace AenEnterprise.FrontEndMvc.Controllers
{
    public class SalesManagementController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateSalesOrder()
        {
            return View();
        }


        public IActionResult UnApproveSalesOrders()
        {
            return View();
        }

        public IActionResult ApprovedSalesOrders()
        {
            return View();
        }

        public IActionResult CreateInvoice()
        {
            return View();
        }

        public IActionResult UnApproveInvoice()
        {
            return View();
        }

        public IActionResult ApprovedInvoice()
        {
            return View();
        }

        public IActionResult CreateDeliveryOrder()
        {
            return View();
        }
        public IActionResult UnApproveDeliveryOrder()
        {
            return View();
        }
        public IActionResult ApproveDeliveryOrder()
        {
            return View();
        }
        public IActionResult CreateDispatch()
        {
            return View();
        }

        public IActionResult DispatchedList()
        {
            return View();
        }
        public IActionResult SalesSummary()
        {
            return View();
        }
    }
}

AenEnterprise/AenEnterprise.FrontEndMvc/Controllers/SalesOrderReportController.cs
using AenEnterprise.DomainModel.SalesManagement;
using AenEnterprise.ServiceImplementations.Interface;
using AspNetCore.Reporting;
using AspNetCore.Reporting.ReportExecutionService;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace AenEnterprise.FrontEndMvc.Controllers
{
    public class SalesOrderReportController : Controller
    {
        string connectionString;
        private readonly IWebHostEnvironment _env;
        private readonly ISalesOrderService _salesOrderService;

        public SalesOrderReportController(IWebHostEnvironment env, ISalesOrderService salesOrderService)
        {
            connectionString= "Data Source=.\\SQLEXPRESS;Initial Catalog=AenDbEnterprise;Integrated Security=True;";
            _env = env;
            _salesOrderService = salesOrderService;
        }

        public IActionResult GetSalesOrder()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }
        public FileContentResult GetSalesOrderById(int salesOrderId)
        {
           
            string query = "SELECT * FROM spGetOrderItemsBySalesOrderId WHERE @SalesOrderId=" + salesOrderId;

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                using (SqlCommand cmd = new SqlCommand("spGetOrderItemsBySalesOrderId", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure; ;
                    cmd.Parameters.Add("@SalesOrderId", SqlDbType.Int).Value = salesOrderId;
                    using (SqlDataAdapter sqlAdapt = new SqlDataAdapter(cmd))
                    {
                       
                        string mimeType = "application/pdf";
                        string reportPath = _env.WebRootPath + "\\Reports\\SalesOrderDetails.rdlc";
                        var localReport = new LocalReport(reportPath);

                        try
                        {
                            // Fetch data from the database and fill a DataTable
                            DataTable dataTable = new DataTable();
                            sqlAdapt.Fill(dataTable);

                            localReport.AddDataSource("DataSetSales", dataTable);

                            var result = localReport.Execute(RenderType.Pdf, 1, null, mimeType);
                            return File(result.MainStream, mimeType);

                            //this line if I want open report in current page
                            //return File(result.MainStream, mimeType, "SalesOrderReport.pdf");
                        }
                        catch (Exception ex)
                        {
                            // Log exceptions to a file or preferred logging mechanism
                            Console.WriteLine("Error: " + ex.Message);
                            throw; // Propagate the exception if needed
                        }
                    }
                }

            }
        }

        public FileContentResult GetInvoiceBySalesOrderId(int invoiceId)
        {
            string query = "SELECT * FROM spGetInvoiceBySalesOrderId WHERE @InvoiceId=" + invoiceId;

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                using (SqlCommand cmd = new SqlCommand("spGetInvoiceBySalesOrderId", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure; ;
                    cmd.Parameters.Add("@InvoiceId", SqlDbType.Int).Value = invoiceId;
                    using (SqlDataAdapter sqlAdapt = new SqlDataAdapter(cmd))
                    {

                        string mimeType = "application/pdf";
                        string reportPath = _env.WebRootPath + "\\Reports\\InvoiceDetails.rdlc";
                        var localReport = new LocalReport(reportPath);

                        try
                        {
                            // Fetch data from the database and fill a DataTable
                            DataTable dataTable = new DataTable();
                            sqlAdapt.Fill(dataTable);

                            localReport.AddDataSource("DataSetSales", dataTable);

                            var result = localReport.Execute(RenderType.Pdf, 1, null, mimeType);
                            return File(result.MainStream, mimeType);

                            //this line if I want open report in current page
                            //return File(result.MainStream, mimeType, "SalesOrderReport.pdf");
                        }
                        catch (Exception ex)
                        {
                            // Log exceptions to a file or preferred logging mechanism
                            Console.WriteLine("Error: " + ex.Message);
                            throw; // Propagate the exception if needed
                        }
                    }
                }

            }
        }

        public FileContentResult GetDeliveryOrderBySalesOrderId(int salesOrderId)
        {
            string query = "SELECT * FROM spGetDeliveryOrderBySalesOrderId WHERE @SalesOrderId=" + salesOrderId;

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                using (SqlCommand cmd = new SqlCommand("spGetDeliveryOrderBySalesOrderId", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure; ;
                    cmd.Parameters.Add("@SalesOrderId", SqlDbType.Int).Value = salesOrderId;
                    using (SqlDataAdapter sqlAdapt = new SqlDataAdapter(cmd))
                    {

                        string mimeType = "application/pdf";
                        string reportPath = _env.WebRootPath + "\\Reports\\DeliveryOrderDetails.rdlc";
                        var localReport = new LocalReport(reportPath);

                        try
                        {
                            // Fetch data from the database and fill a DataTable
                            DataTable dataTable = new DataTable();
                            sqlAdapt.Fill(dataTable);

                            localReport.AddDataSource("DataSetSales", dataTable);

                            var result = localReport.Execute(RenderType.Pdf, 1, null, mimeType);
                            return File(result.MainStream, mimeType);

                            //this line if I want open report in current page
                            //return File(result.MainStream, mimeType, "SalesOrderReport.pdf");
                        }
                        catch (Exception ex)
                        {
                            // Log exceptions to a file or preferred logging mechanism
                            Console.WriteLine("Error: " + ex.Message);
                            throw; // Propagate the exception if needed
                        }
                    }
                }

            }
        }
        public FileContentResult SalesOrderDetails()
        {
            string query = "SELECT * FROM View_GetAllSalesOrderWithOrderItems";
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                using (SqlDataAdapter sqlAdapt = new SqlDataAdapter(query, conn))
                {
                    string mimeType = "application/pdf";
                    string reportPath = _env.WebRootPath + "\\Reports\\SalesOrderDetails.rdlc";
                    var localReport = new LocalReport(reportPath);

                    try
                    {
                        // Fetch data from the database and fill a DataTable
                        DataTable dataTable = new DataTable();
                        sqlAdapt.Fill(dataTable);


                     
                        localReport.AddDataSource("DataSetInvoice", dataTable);

                        var result = localReport.Execute(RenderType.Pdf, 1, null, mimeType);
                        return File(result.MainStream, mimeType);
                    }
                    catch (Exception ex)
                    {
                        // Log exceptions to a file or preferred logging mechanism
                        Console.WriteLine("Error: " + ex.Message);
                        throw; // Propagate the exception if needed
                    }
                }
            }
        }
    }
}

AenEnterprise/AenEnterprise.FrontEndMvc/Views/UnApproveSalesOrders.cshtml
@{
    ViewData["Title"] = "UnApproveSalesOrders";
    Layout = "~/Views/Shared/SalesSearchCriteria_Layout";
}
 


<script>
    $(document).ready(function () {
        $("#checkedAll").change(function () {
            if (this.checked) {
                $(".checkSingle").each(function () {
                    this.checked = true;
                })
            } else {
                $(".checkSingle").each(function () {
                    this.checked = false;
                })
            }
        });
        $(".checkSingle").click(function () {
            if ($(this).is(":checked")) {
                var isAllChecked = 0;
                $(".checkSingle").each(function () {
                    if (!this.checked)
                        isAllChecked = 1;
                })
                if (isAllChecked == 0) { $("#checkedAll").prop("checked", true); }
            }
            else {
                $("#checkedAll").prop("checked", false);
            }
        });
    });
    
    async function ChangeApprovalStatusByChecked() {
        var chkChecked = $("input[name='checkSingle']:checked").length;
        if (chkChecked >= 1) {
            var statusId = $("#ddlStatusId").val(); // Retrieve the selected approval ID
            var postArr = [];
 
            $("input[name='checkSingle']:checked").each(function () {
                var orderItemId = $(this).val();
                var salesOrderId = $(this).closest(".orderitem-cell-data-container").find("#spnSalesOrderId").text();
                var formrequests = {
                    StatusId: statusId,
                    SalesOrderId: salesOrderId,
                    OrderItemId: orderItemId
                    
                };
                
                postArr.push(formrequests);
            });

            try {
                await $.ajax({
                    url: '/api/SalesOrder/ApproveOrderItems',
                    type: 'POST',
                    dataType: 'json',
                    data: JSON.stringify(postArr),
                    contentType: 'application/json; charset=utf-8',
                    success: async function (datas) {
                        
                        const pageSize = 6;
                        const currentPage = parseInt($('.page-link.active').text().trim());
                        
                        alert(currentPage);
                        getSalesOrders(currentPage,6); // Ensure the page size is set as desired (e.g., 6)
                    },
                    error: function (xhr, textStatus, errorThrown) {
                        console.error("Error updating approval status: " + textStatus + " - " + errorThrown);
                        // Handle error response as needed
                    }
                });
            } catch (error) {
                console.error("Error updating approval status: " + error.message);
            }
        } else {
            alert("Please select sales orders to update approval status!");
        }
    }
</script>
 
<div class="salesOrder-container">
    <div class="salesOrder-item-header-top">
        <div class="approval-criteria">
            <select id="ddlStatusId">
                <option value="2">Approve</option>
                <option value="4">Reject</option>
            </select>
            <a href="#" id="changeStatusButton" onclick="Javascript:ChangeApprovalStatusByChecked()">Change Status</a>
        </div>
    </div>




    <div class="salesOrder-item-content">
        <div class="salesOrder-cell-marge-2">
             <div class="totalItemsFound"></div>
        </div>
        <div class="salesOrder-cell-content">
          
        </div>
        <div class="salesOrder-cell-content">
          
        </div>
        <div class="salesOrder-cell-content">
            <input type="checkbox" name="checkedAll" class="input-group-sm" id="checkedAll" /> Select All
        </div>
    </div>

    <div id="salesOrderElement"></div>
    <script type="text/html" id="salesOrdersTemp">
                {#foreach $T.salesOrders as record}
        <div class="salesOrder-item-data">
            <div class="salesOrder-cell">
               <a href="@Url.Action("GetSalesOrderById", "SalesOrderReport")?salesOrderId={$T.record.id}">{$T.record.salesOrderNo}</a>
            </div>
            <div class="salesOrder-cell">
                        {$T.record.customerName}
            </div>
            <div class="salesOrder-cell">
                        {$T.record.orderDateInFormat}
            </div>
            <div class="salesOrder-cell">
             @*     <a href="@Url.Action("CreateInvoice", "SalesManagement")/{$T.record.id}">Create Invoice</a><br> *@
            </div>
            <div class="salesOrder-cell">
                   
            </div>
        </div>

        <div class="orderItems-container">
            <div class="orderitem-cell-header-container">
                    <div class="orderitem-cell-header">
                        Item Id
                    </div>
                    <div class="orderitem-cell-header">
                           Product Name
                    </div>
                    <div class="orderitem-cell-header">
                        Price
                    </div>
                    <div class="orderitem-cell-header">
                           Quantity
                    </div>
                    <div class="orderitem-cell-header">
                        Invoice Quantity
                    </div>
                    <div class="orderitem-cell-header">
                         Balance Quantity
                    </div>
                    <div class="orderitem-cell-header">
                       Amount
                    </div>
                    <div class="orderitem-cell-header">
                      
                    </div>

                </div>
                 {#foreach $T.record.orderItems as oi}

            <div class="orderitem-cell-data-container">
                <div class="orderitem-cell-data">
                       <span id="spnOrderItemid">{$T.oi.id}</span>   <span id="spnSalesOrderId">{$T.oi.salesOrderId}</span>
                </div>
                <div class="orderitem-cell-data">
                        {$T.oi.productName}
                </div>
                <div class="orderitem-cell-data">
                        {$T.oi.price}
                </div>
                <div class="orderitem-cell-data">
                            {$T.oi.quantityInFormat} {$T.oi.unitName}
                </div>
                <div class="orderitem-cell-data">
                        {$T.oi.invoiceQuantityInFormat} {$T.oi.unitName}
                </div>
                <div class="orderitem-cell-data">
                        {$T.oi.balanceQuantityInFormat} {$T.oi.unitName}
                </div>
                <div class="orderitem-cell-data">
                          {$T.oi.amountInFormat}
                </div>
                <div class="orderitem-cell-data">
                       <input type="checkbox" name="checkSingle" value="{$T.oi.id}" class="checkSingle" id="chkSingle" />
                </div>
            </div>
                {#/for}
        </div>
                  {#/for}
    </script>
</div>
<div class="pagebar-container">
     <div class="totalItemsFound"></div> <div class="paging">
    </div>
</div>